sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AkX7buOWrEDNj/+pWpD1wvCtxkLDn2tKektUaMP5BzwDdhuWiRqU6ySbFiXkTx1WnmciJBEpx3f/HtAdv80FRuHW6X5P8xD6Snhvtpf/APxPAiT0Z9TK3eos2TGJq2qxGBEf2bhu/mx4ArrW2W8gMJWKsIJzVvblYcG7AwwrCvCQyDj1pXdLAJoS5B+Ta5JjhBzLryl68U3UzSwHkAeNyPuv4TQuWi5TaB/LK1xBexcAWxqpxRrZkj9yb6Ijh2kpcJ3wxmJ9bYqP3aM43xoYfMg5vk+oPOQv3gB2g/hy7lqSEIW9X3DS1h38YXEVR3kDHzq4JF35cUjga9t/5lAQ8bqwgGJp9LYS7qFweSoDOiVhchsy2eHE5mhtFGNTYbAYlOs77WgFl+eGDV9+Zfr+6hlwg6hTGTk4U85yxKdPSzy34TXee2yNUgFQCJEthLTDwdBtUkc5Wf1BQYHIFYpMRA3GBZyRs4x+5sfr68U7mkqcNg/pzHLMTu8pEfeTckCJKx00cP4f/HSKDZgd8n7qkLMAERWEVuN3dGJoczR3L1CTs75kcqK8YcR5CgxMQekYu9AViU6sXpzhorVbWpMWokTNBrl0abPjTMLuvEUax1uF04v2oxrauuiRi2hk2qM+R1W77I7wuFLe71Z1hgJIoVlkCbnOnWUz7NK8jfRUdHc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Around-the-World-on-a-Bicycle-Volume-I-From-San-Francisco-to-Teheran_5136
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy